server:
  port: 8003
spring:
  application:
    name: hug-demo-server
  cloud:
    config:
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: hug-config
    profiles:
      active: dev
    bus:
      enabled: true
      trace:
        enabled: true
  redis:
    host: 120.79.197.55
    password:
    port: 6379
    timeout: 10000 # 连接超时时间（毫秒）
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
        max-idle: 8 # 连接池中的最大空闲连接默认 8
        min-idle: 0 # 连接池中的最小空闲连接默认 0
  rabbitmq:
    host: 120.79.197.55
    port: 5672
    username: guest
    password: guest
    listener: # 这里配置了重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  datasource:
    url: jdbc:mysql://120.79.197.55:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: P@ssw0rd
    # 初始连接数
    initial-size: 10
    # 最大连接池数量
    max-active: 100
    # 最小连接池数量
    min-idle: 10
    # 配置获取连接等待超时的时间
    max-wait: 60000
  zipkin:
    base-url: http://localhost:8088
    enabled: true
    #发送方式，没有默认值，一定要配置
    sender:
      type: web
  #    sender:
#      type: rabbit
  sleuth:
    sampler:
      #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）
      probability: 1
#mybatis plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hug.demo.api.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 1
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: true
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
  #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
test:
  bus:
    name: abc
