server:
  port: 8010
spring:
  application:
    name: hug-gateway
  cloud:
    config:
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: hug-config
  profiles:
    active: dev
management:
  #spring boot admin监控配置
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS