server:
  port: 8005
spring:
  application:
    name: hug-gateway
  cloud:
    gateway:
      #开启服务注册和发现的功能
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #路由
      routes:
        - id: hug-demo-client
          uri: lb://hug-demo-client
          predicates:
            - Path=/demo/**
          filters:
          #在转发之前将/demo去掉
          #- StripPrefix=1
#            - name: RateLimiter
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/controller
  redis:
    host: 120.79.197.55
    password:
    port: 6379
    timeout: 10000 # 连接超时时间（毫秒）
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
        max-idle: 8 # 连接池中的最大空闲连接默认 8
        min-idle: 0 # 连接池中的最小空闲连接默认 0
  hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/