server:
  port: 8002
spring:
  application:
    name: hug-demo-client
  cloud:
#    name: hug-config
    config:
#      uri: http://localhost:8888
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: hug-config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/