server:
  port: 8888

spring:
  application:
    name: hug-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hugwh/hug-config-remote.git
          search-paths: '{application}'
          username: hugwh
          password: Hwh118122
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/