server:
  port: 8002
spring:
  application:
    name: hug-demo-client
  cloud:
    config:
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: hug-config
    profiles:
      active: dev
  zipkin:
    base-url: http://localhost:8088
    enabled: true
    #发送方式，没有默认值，一定要配置
    sender:
      type: web
#    sender:
#      type: rabbit
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）
      probability: 1
  rabbitmq:
    host: 120.79.197.55
    port: 5672
    username: guest
    password: guest
    listener: # 这里配置了重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
#开启swagger服务
swagger:
  enable: true
  basePackage: "com.hug.demo.client"
management:
  #spring boot admin监控配置
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

